SELECT
    COD_BASE AS 'Código Base',
    NOME_BASE AS 'Nome Base',
    COD_MATERIAL AS 'Código Material',
    ISNULL(PRODUTO, DSC_MATERIAL) AS 'Material',
    COD_CLIENTE AS 'Código Cliente',
    NOME_CLIENTE_ AS 'Nome Cliente',
    COD_REGIAO_CLIENTE AS 'uf_cliente',
    REGIAO_CLIENTE AS 'Estado Cliente',
    MUNICIPIO_CLIENTE AS 'Município Cliente',
    CAST(VOLUME AS FLOAT) AS 'Volume',
    CAST(LUCRO_BRUTO_CPV AS DECIMAL(30, 2)) AS 'LB Reposição',
    CAST(LUCRO_CONTABIL AS DECIMAL(30, 2)) AS 'LB Contábil',
    SETOR_ATIVIDADE AS 'nome_atividade',
    GRUPO_CLIENTE AS setor_industrial_cliente,
    CLIENTE_VISAO_VENDAS AS 'nome_cliente_pagador',
    TIPO_DOCUMENTO AS 'nome_tipo_doc_venda',
    COD_REGIAO_BASE AS 'uf_base',
    REGIAO_BASE AS 'Estado Base',
    COD_MUNICIPIO_BASE AS 'Municipio Base',
    ORG_VENDAS AS 'Organizacao Vendas',
    COD_CANAL_DISTRIBUICAO AS 'cod_canal_distribuicao',
    CANAL_DISTRIBUICAO AS 'Canal Distribuicao',
    DSC_INCOTERMS AS incoterms,
    TIPO_PRODUTO AS 'Lubes ou Diesel',
    SETOR_ATIVIDADE AS 'nome_setor_atividade',
    CAST(CPV_REPOSICAO AS DECIMAL(30, 2)) AS 'CPV Rep',
    CAST(CPV_FECHAMENTO AS DECIMAL(30, 2)) AS 'CPV Fechamento',
    CAST(FATURAMENTO_REAL AS DECIMAL(30, 2)) AS faturamento_real,
    CAST(VALOR_ENCARGOS AS DECIMAL(30, 2)) AS encargos,
    CAST(RECEITA_LIQUIDA AS DECIMAL(30, 2)) AS 'Receita líquida',
    PAIS_CLIENTE_ AS 'País Cliente',
    PAIS_CLIENTE_ AS 'Descrição País Cliente',
    CAST(CPV_PARCIAL AS DECIMAL(30, 2)) AS 'CPV Parc',
    CAST(REPASSE_ICMS AS DECIMAL(30, 2)) AS 'Repasse ICMS',
    CAST(RECEITA_BRUTA_QA AS DECIMAL(30, 2)) AS 'Receita Bruta',
    CAST(PRECO_MEDIO_NF AS DECIMAL(30, 2)) AS 'Preço MedNF',
    CAST(VALOR_DESCONTO AS DECIMAL(30, 2)) AS desconto,
    CAST(ICMS_TOTAL AS DECIMAL(30, 2)) AS 'Repasse ICMS Total',
    CAST(PIS_COFINS AS DECIMAL(30, 2)) AS repasse_pis_confis,
    CAST(RECEITA_BRUTA_COM_ICMS AS DECIMAL(30, 2)) AS receita_bruta_total,
    CAST(ANO AS BIGINT) AS 'Ano',
    TRY_CAST(ANO_MES AS BIGINT) AS 'Mês',
    TRY_CAST(DATA_VENDA AS DATE) AS 'Dt Venda',
    TRY_CAST(PERCENTUAL_RECEITA AS DECIMAL(30, 2)) AS percen_receita_bruta,
    TRY_CAST(CT AS DECIMAL(30, 2)) AS 'CT',
    TRY_CAST(LM AS DECIMAL(30, 2)) AS 'LM',
    TRY_CAST(CT_LM AS DECIMAL(30, 2)) AS 'Total CT LM',
    TRY_CAST(LB_REP_CTLM_NX AS DECIMAL(30, 2)) AS 'LB Reposição + CTLM',
    CODIGO AS 'Prod - Código',
    PRODUTO AS 'Prod - Produto',
    GRUPO_PRODUTO AS 'Prod - Grupo Produto',
    CATEGORIA_1 AS prod_categoria_1,
    CATEGORIA_2 AS prod_categoria_2,
    CATEGORIA_3 AS prod_categoria_3,
    TIPO_PRODUTO_BASICO AS prod_tipo_produto_basico,
    FAMILIA_PRODUTO AS 'Prod - Família de Produtos',
    EMBALAGEM_SIMPLES AS 'Prod - Embalagem Simples',
    SLOW_MOVER AS 'Slow Mover',
    TIPO_BASE AS 'Prod - Tipo de Base',
    VISCOSIDADE AS 'Prod - Viscosidade',
    CATEGORIA_SIMPLES AS 'Prod - Categoria simples',
    EMBALAGEM AS 'Prod - Embalagem',
    CATEGORIA_IBP AS prod_categoria_ibp,
    CATEGORIA_IBP_SIMPLES AS prod_categoria_ibp_simples,
    REPORTADO_IBP AS prod_reportado_anp,
    CATEGORIA_ANTIGA AS prod_categoria_antiga,
    CLASSIFICACAO AS prod_classificacao,
    LITRAGEM AS prod_litragem,
    ATIVO_VENDA AS prod_ativo_venda,
    ATIVO_PRODUTO AS prod_ativo_produto,
    GRUPO_PRODUTO_UNIFICADO AS prod_grupo_produto_unificado,
    TIPO_PRODUCAO AS prod_tipo_producao,
    ORIGEM_PRODUCAO AS prod_origem_producao,
    MARCA AS prod_marca,
    PRODUTO_PREMIUM AS prod_produto_premium,
    CNPJ_CLIENTE AS 'CNPJ Cliente',
    VP AS 'DIR',
    DIR AS 'GE',
    GER AS '2º Nivel',
    ZV AS '3º Nível',
    SZV AS centro_lucro_n5,
    PRODUTO_NVL1 AS 'PRODUTO_NVL1',
    PRODUTO_NVL2 AS 'PRODUTO_NVL2',
    PRODUTO_NVL3 AS 'PRODUTO_NVL3',
    PRODUTO_NVL4 AS 'PRODUTO_NVL4',
    PRODUTO_NVL5 AS 'PRODUTO_NVL5',
    SEGMENTO_1 AS 'SEGMENTO_NVL0',
    SEGMENTO_2 AS 'SEGMENTO_NVL1',
    SEGMENTO_3 AS 'SEGMENTO_NVL2',
    SEGMENTO_4 AS 'SEGMENTO_NVL3',
    CASE
        WHEN NOME_DA IS NOT NULL THEN 'FLAG_DA'
    END AS 'Flag DA',
    CANAL AS 'Canal',
    CANAL_OWNER AS 'Canal Owner',
    MODELO_NEGOCIO AS 'Modelo de Negócio',
    TRY_CAST(MARGEM_REP_M3 AS DECIMAL(30, 2)) AS 'Margem Reposição Unitaria',
    TRY_CAST(FRETE AS DECIMAL(30, 2)) AS 'Frete',
    NOME_KAM AS ev_da,
    TIPO_CLIENTE AS tipo_cliente,
    CT_COM_IMPOSTO AS ct_com_imposto,
    LM_COM_IMPOSTO AS lm_com_imposto,
    CT_LM_COM_IMPOSTO AS ctlm_com_imposto,
    NX AS nx,
    NX_COM_IMPOSTO AS nx_com_impostos,
    CLIENTES_RISEL AS cliente_risel,
    SEGMENTO_B2B AS segmentacao_b2b,
    DATA_ATUALIZACAO AS 'Data_Atualizacao'
FROM [LDW].[VW_SELLIN];
